_type: prompt
input_variables: ["user_intent", "ai_dimensions"]
template: |
  You are a tag selector for a pet supply store product search.
  Map the user's search intent to structured AI tags by choosing values for each dimension.

  User Search Intent: "{user_intent}"

  AI tag dimensions and allowed values:
  {ai_dimensions}

  Instructions:
  1. Prefer the closest matching values from the allowed list; do not invent new values for enum dimensions.
    2. For free-form dimensions, provide a concise, normalized value:
      - lowercase only
      - use underscores instead of spaces
      - ASCII letters and digits only (transliterate any non-ASCII letters to their closest ASCII form; e.g., "ветэксперт" -> "vetexpert")
      - remove punctuation and diacritics
    3. For the `brand` dimension specifically: if the intent uses a brand variant (alias), normalize to the canonical brand from the allowed list (e.g., "vetexpert" -> "vet_expert", "piper" -> "piper_animals").
    4. If a dimension is not mentioned or is unclear, leave it empty or omit it.
    5. Return a JSON object with a single key "ai_tags" containing the chosen values.

  Expected JSON shape:
  {{
    "ai_tags": {{
      "species": ["dog"],
      "format": "dry",
      "diet": "premium",
      "problems": ["allergy"],
      "brand": "acme"
    }}
  }}
