require 'spree_core'
require 'spree_extension'
require 'spree_vetfort_extension_v5/engine'
require 'spree_vetfort_extension_v5/version'
require 'spree_vetfort_extension_v5/configuration'
require 'ssrf_filter'
require 'langchain'
require 'wikipedia-client'
require 'down'
require 'tempfile'
require 'aasm'
require 'faker'
require 'telegram/bot'
require 'view_component'

# RAG / vector search (pgvector + neighbor)
require 'pgvector'
require 'neighbor'
