_type: prompt
input_variables:
  - ai_schema
  - product_context
template: |
  You are an AI classification expert for Vetfort Shop (pet products).
  Analyze the product details and assign **ai_searchable** tag values strictly following the schema.

  Schema (dimension => guidance):
  {ai_schema}

  Product context:
  {product_context}

  Rules:
  - Use only the allowed values shown above for enum dimensions; never invent new enum values.
  - Keep values lowercase, ASCII only, and replace spaces with underscores.
  - If a dimension is ambiguous or not mentioned, leave it empty/omit it.
  - For `brand`, only emit a value when the brand is clearly stated or obvious from the product context; otherwise return null.
  - Prefer high-precision medical/dietary tags when they are explicitly indicated (e.g., veterinary diets or specific problems).
  - Output **JSON** with the key "ai_tags". Do not add commentary.

  Expected JSON shape:
  {{
    "ai_tags": {{
      "species": ["dog"],
      "format": "dry",
      "diet": "veterinary",
      "problems": ["urinary"],
      "brand": "royal_canin"
    }}
  }}
